name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
 
      # ===== LOGIN REGISTRY =====  
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ===== BUILD & PUSH IMAGE (VERSIONED) =====    
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/namtieu/cicd-demo:latest
            ghcr.io/namtieu/cicd-demo:${{ github.sha }}
  
      # ===== CI VERSION LOG =====
      - name: Log build version
        run: |
          echo "===================================="
          echo "CI BUILD VERSION"
          echo "Repository : $GITHUB_REPOSITORY"
          echo "Branch     : $GITHUB_REF_NAME"
          echo "Commit SHA : $GITHUB_SHA"
          echo "Image      : ghcr.io/namtieu/cicd-demo:$GITHUB_SHA"
          echo "Build time : $(date -u)"
          echo "===================================="

      - name: Deploy to Ubuntu Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # docker pull ghcr.io/namtieu/cicd-demo:latest
            # docker rm -f cicd-demo || true
            # docker run -d \
            #   --name cicd-demo \
            #   -p 80:3000 \
            #   ghcr.io/namtieu/cicd-demo:latest
            VERSION=${{ github.sha }}
            IMAGE=ghcr.io/namtieu/cicd-demo:$VERSION

            echo "===================================="
            echo "DEPLOY INFO"
            echo "Version : $VERSION"
            echo "Image   : $IMAGE"
            echo "Time    : $(date)"
            echo "===================================="

            docker pull $IMAGE
            docker rm -f cicd-demo || true
            docker run -d \
              --name cicd-demo \
              -p 80:3000 \
              -e APP_VERSION=$VERSION \
              $IMAGE